services:
  database:
    volumes:
      - mariadb:/var/lib/mysql
    container_name: app-db
    image: mariadb:10.6.16
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT:-3306}:3306
    networks:
      net:

  php:
    volumes:
      - ./backend:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    container_name: cli-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    depends_on:
      - "database"
    networks:
      net:

  ws-backend:
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf
    container_name: app-wsbackend
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "${BACKEND_PORT:-12000}:12000"
    depends_on:
      - "php"
    networks:
      net:

  composer:
    volumes:
      - ./backend:/app
      - /etc/localtime:/etc/localtime:ro
    container_name: cli-composer
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    depends_on:
      - "ws-backend"
    networks:
      net:

  node:
    volumes:
      - ./frontend:/app
    container_name: cli-node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    depends_on:
      - "ws-backend"
    networks:
      net:

  ws-frontend:
    volumes:
      - ./frontend:/var/www/html
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    container_name: app-wsfrontend
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "${FRONTEND_PORT:-10000}:10000"
    depends_on:
      - "node"
    networks:
      net:

networks:
  net:
    name: app-network
    external: false

volumes:
  mariadb:
    name: db-data